echo "        <hive_observation>"
echo "                <hive_id>$HOST</hive_id>"
echo "                <hive_observation_time>$DATE</hive_observation_time>"
echo "                <hive_weight_lbs>$SCALE</hive_weight_lbs>"
echo "                <hive_temp_c>$TEMP</hive_temp_c>"
echo "                <hive_ambient_temp_c>$AMBIENT</hive_ambient_temp_c>"
echo "                <hive_relative_humidity>$HUMIDITY</hive_relative_humidity>"
echo "                <hive_ambient_relative_humidity>$HUMIDITY_2</hive_ambient_relative_humidity>"
echo "        </hive_observation>"

